#?????
# properties ??
#server.port = 8081

# yml ??
server:
  port: 8081

user:
  name: devil
  age: 19
  happy: false
  birthday: 2024/3/15
  maps: {k1: v1,k2: v2,k3: v3}
  list:
    - code
    - game
    - run
  person:
    name: huang
    age: 40

