#端口
server:
  port: 9091
  #项目路径
  servlet:
    context-path: /api


#数据库
spring:
  datasource:
    url: jdbc:mysql://192.168.33.164:3306/easy_test?springboot&useUnicode=true&useSSL=false&serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis
mybatis:
  #类名简写
  type-aliases-package: com.devil.entity.pojo
  mapper-locations: classpath:mappers/*.xml
  #logger
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
